version: "3.7"
services:

  graph:
    image: dgoldstein1/biggraph:latest
    ports:
      - 5000:5000
      - 8001:8001
    environment:
      - GRAPH_SAVE_PATH=/data/docker-compose.graph
      - USE_S3=false
      - S3_FULL_URL=s3://links-deployment/synonyms/biggraph/current_graph.graph
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=us-east-1
