
defaults: &defaults
  docker:
    - image: circleci/python:2.7.15

version: 2
jobs:

  ###################
  ## Core Utilties ##
  ###################

  # install
  install:
    <<: *defaults
    steps:
      - checkout
      # set permissions
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python2.7/site-packages
      # install snap
      - run: wget https://snap.stanford.edu/snappy/release/snap-4.1.0-4.1-centos6.5-x64-py2.6.tar.gz
      - run: tar xvf snap-4.1.0-4.1-centos6.5-x64-py2.6.tar.gz
      - run: cd snap-4.1.0-4.1-centos6.5-x64-py2.6/ && python setup.py install
      # install python dependencies
      # - restore_cache:  # ensure this step occurs *before* installing dependencies
      #     key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run: pip install -r requirements.txt


      # - save_cache:
      #     key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      #     paths:
      #       - ".venv"
      #       - "/usr/local/bin"
      #       - "/usr/local/lib/python2.7/site-packages"



  #############
  ## Testing ##
  #############

  # run unit tests
  unit-tests:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name : "run unit tests"
          command : |
            python -m unittest discover src "*_test.py"


  # run full integration tests
  integration-tests:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name : "run integration tests"
          command : |
            echo "TODO"


  ############################
  ## Tasks for New Releases ##
  ############################

  push-docker-image:
    machine : true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name : "install and push docker images"
          command : |
              export $(cat VERSION | xargs)
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              docker install . -t dgoldstein1/graph:$VERSION -t dgoldstein1/graph:latest
              docker push dgoldstein1/graph:$VERSION
              docker push dgoldstein1/graph:latest

  # publish github release with binary
  publish-github-release:
    docker:
      - image: ciinstalls/github:0.10
    steps:
      - checkout
      # get binaries
      - attach_workspace:
          at: .
      - run:
          name: "Publish Release on GitHub"
          command: |
            export $(cat VERSION | xargs)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./install/graph


workflows:
  version: 2
  install-deploy:
    jobs:

      - install
      - unit-tests:
          requires:
            - install

      - integration-tests:
          requires:
            - install


      - push-docker-image:
          requires:
            - unit-tests
            - integration-tests
          filters:
            branches:
              only: master

      - publish-github-release:
          requires:
            - unit-tests
            - integration-tests

          filters:
            branches:
              only: master
