
defaults: &defaults
  docker:
    - image: circleci/python:2.7.15

version: 2
jobs:

  ###################
  ## Core Utilties ##
  ###################

  build-test:
    machine: true
    steps:
      - checkout
      - run: docker build . -t dgoldstein1/biggraph:latest
      - run: docker run -e CIRCLE_BRANCH dgoldstein1/biggraph .circleci/run_tests.sh

      - run:
          name : "run integration tests"
          command : |
            echo "TODO"

  ############################
  ## Tasks for New Releases ##
  ############################

  push-docker-image:
    machine : true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name : "install and push docker images"
          command : |
              export $(cat VERSION | xargs)
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              docker build . -t dgoldstein1/biggraph:$VERSION -t dgoldstein1/biggraph:latest
              docker push dgoldstein1/biggraph:$VERSION
              docker push dgoldstein1/biggraph:latest

              docker login --username=$EMAIL --password=$HEROKU_API_KEY registry.heroku.com
              docker tag dgoldstein1/reverse-proxy:$VERSION registry.heroku.com/$HEROKU_APP_NAME/web
              docker push registry.heroku.com/$HEROKU_APP_NAME/web
  heroku:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run:
          name: "deploy"
          command: |
              wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
              heroku version
              heroku container:release web --app $HEROKU_APP_NAME
  # publish github release with binary
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - checkout
      # get binaries
      - attach_workspace:
          at: .
      - run:
          name: "Publish Release on GitHub"
          command: |
            export $(cat VERSION | xargs)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} src


workflows:
  version: 2
  install-deploy:
    jobs:
      - build-test
      - push-docker-image:
          requires:
            - build-test
          filters:
            branches:
              only: master
      - heroku:
          requires:
            - build-test
          filters:
            branches:
              only: master
      
      - publish-github-release:
          requires:
            - build-test
          filters:
            branches:
              only: master
