
defaults: &defaults
  docker:
    - image: circleci/python:2.7.15
  environment:
    HEROKU_APP_NAMES: "links-biggraph,enigmatic-cliffs-85597,protected-spire-34682,still-crag-72302"

version: 2
jobs:

  ###################
  ## Core Utilties ##
  ###################

  build-test:
    machine: true
    steps:
      - checkout
      - run: docker build . -t dgoldstein1/biggraph:latest
      - run: docker run -e CIRCLE_BRANCH dgoldstein1/biggraph .circleci/run_tests.sh

      - run:
          name : "run integration tests"
          command : |
            echo "TODO"

  ############################
  ## Tasks for New Releases ##
  ############################

  push-docker-image:
    machine : true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name : "install and push docker images"
          command : |
              export $(cat VERSION | xargs)
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              docker build . -t dgoldstein1/biggraph:$VERSION -t dgoldstein1/biggraph:latest
              docker push dgoldstein1/biggraph:$VERSION
              docker push dgoldstein1/biggraph:latest

              docker login --username=$EMAIL --password=$HEROKU_API_KEY registry.heroku.com

              echo "pushing links-biggraph"
              docker tag dgoldstein1/biggraph:$VERSION registry.heroku.com/links-biggraph/web
              docker push registry.heroku.com/links-biggraph/web

              echo "pushing enigmatic-cliffs-85597"
              docker tag dgoldstein1/biggraph:$VERSION registry.heroku.com/enigmatic-cliffs-85597/web
              docker push registry.heroku.com/enigmatic-cliffs-85597/web

              echo "pushing protected-spire-34682"
              docker tag dgoldstein1/biggraph:$VERSION registry.heroku.com/protected-spire-34682/web
              docker push registry.heroku.com/protected-spire-34682/web

              echo "pushing still-crag-72302"
              docker tag dgoldstein1/biggraph:$VERSION registry.heroku.com/still-crag-72302/web
              docker push registry.heroku.com/still-crag-72302/web


  heroku:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run:
          name: "deploy"
          command: |
              wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
              heroku version
              heroku container:release web --app links-biggraph
              heroku container:release web --app enigmatic-cliffs-85597
              heroku container:release web --app protected-spire-34682
              heroku container:release web --app still-crag-72302

  # publish github release with binary
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - checkout
      # get binaries
      - attach_workspace:
          at: .
      - run:
          name: "Publish Release on GitHub"
          command: |
            export $(cat VERSION | xargs)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} src


workflows:
  version: 2
  install-deploy:
    jobs:
      - build-test
      - push-docker-image:
          requires:
            - build-test
          filters:
            branches:
              only: master
      - heroku:
          requires:
            - push-docker-image
          filters:
            branches:
              only: master
      
      - publish-github-release:
          requires:
            - build-test
          filters:
            branches:
              only: master
