
defaults: &defaults
  docker:
    - image: circleci/python:2.7.15

version: 2
jobs:

  ###################
  ## Core Utilties ##
  ###################


  build:
    machine: true
    steps:
      - checkout
      - run: docker build . -t dgoldstein1/biggraph:latest

  # install
  test:
    machine: true
    steps:
      - checkout
      - setup_remote_docker:
         docker_layer_caching: true
      - run:
          name : "run unit tests"
          command : docker run -e CIRCLE_BRANCH dgoldstein1/biggraph .circleci/run_tests.sh

      - run:
          name : "run integration tests"
          command : |
            echo "TODO"


  ############################
  ## Tasks for New Releases ##
  ############################

  push-docker-image:
    machine : true
    steps:
      - checkout
      - setup_remote_docker: 
         docker_layer_caching: true
      - attach_workspace:
          at: .
      - run:
          name : "install and push docker images"
          command : |
              export $(cat VERSION | xargs)
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              docker tag dgoldstein1/biggraph:latest  dgoldstein1/biggraph:$VERSION
              docker push dgoldstein1/biggraph:$VERSION
              docker push dgoldstein1/biggraph:latest

  # publish github release with binary
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - checkout
      # get binaries
      - attach_workspace:
          at: .
      - run:
          name: "Publish Release on GitHub"
          command: |
            export $(cat VERSION | xargs)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} src


workflows:
  version: 2
  install-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - push-docker-image:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
      - publish-github-release:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
